function pac_autoremove --wraps=sudo\ pacman\ -Rcs\ appstream-glib\nasciidoc\nblueprint-compiler\nboost\ncatch2\nchrpath\ncmark\ncython\ndejagnu\ndmraid\ndoxygen\ndpkg\ndvisvgm\nelectron\nelectron22\nextra-cmake-modules\nffnvcodec-headers\nfontforge\ngn\ngperf\ngptfdisk\nhelp2man\nhttpdirfs\nhttpfs2-2gbplus\ninetutils\ninkscape\njava-environment-common\njre-openjdk-headless\nkpipewire\nlibindicator-gtk3\nlibmfx\nliborcus\nlibxcrypt-compat\nlld\nlua-lgi\nlua-lpeg\nmeson\nopencv\nostree\np7zip\npython-backcall\npython-exceptiongroup\npython-fixtures\npython-flask-compress\npython-flask-gravatar\npython-flask-migrate\npython-flask-paranoid\npython-flask-security-too\npython-flit-core\npython-gssapi\npython-hurry-filesize\npython-jaraco.test\npython-ldap3\npython-mock\npython-poetry-dynamic-versioning\npython-rapidfuzz-capi\npython-rfc3986\npython-scikit-build\npython-setuptools-scm\npython-simplejson\npython-sshtunnel\npython-testpath\npython-testtools\npython-toml\npython-xlib\nrpcsvc-proto\nrustup\nscdoc\nsysfsutils\ntinycompress\ntllist\nvala\nvulkan-validation-layers\nwlroots\nxtrans --description alias\ pac_autoremove\ sudo\ pacman\ -Rcs\ appstream-glib\nasciidoc\nblueprint-compiler\nboost\ncatch2\nchrpath\ncmark\ncython\ndejagnu\ndmraid\ndoxygen\ndpkg\ndvisvgm\nelectron\nelectron22\nextra-cmake-modules\nffnvcodec-headers\nfontforge\ngn\ngperf\ngptfdisk\nhelp2man\nhttpdirfs\nhttpfs2-2gbplus\ninetutils\ninkscape\njava-environment-common\njre-openjdk-headless\nkpipewire\nlibindicator-gtk3\nlibmfx\nliborcus\nlibxcrypt-compat\nlld\nlua-lgi\nlua-lpeg\nmeson\nopencv\nostree\np7zip\npython-backcall\npython-exceptiongroup\npython-fixtures\npython-flask-compress\npython-flask-gravatar\npython-flask-migrate\npython-flask-paranoid\npython-flask-security-too\npython-flit-core\npython-gssapi\npython-hurry-filesize\npython-jaraco.test\npython-ldap3\npython-mock\npython-poetry-dynamic-versioning\npython-rapidfuzz-capi\npython-rfc3986\npython-scikit-build\npython-setuptools-scm\npython-simplejson\npython-sshtunnel\npython-testpath\npython-testtools\npython-toml\npython-xlib\nrpcsvc-proto\nrustup\nscdoc\nsysfsutils\ntinycompress\ntllist\nvala\nvulkan-validation-layers\nwlroots\nxtrans
  sudo pacman -Rcs appstream-glib
asciidoc
blueprint-compiler
boost
catch2
chrpath
cmark
cython
dejagnu
dmraid
doxygen
dpkg
dvisvgm
electron
electron22
extra-cmake-modules
ffnvcodec-headers
fontforge
gn
gperf
gptfdisk
help2man
httpdirfs
httpfs2-2gbplus
inetutils
inkscape
java-environment-common
jre-openjdk-headless
kpipewire
libindicator-gtk3
libmfx
liborcus
libxcrypt-compat
lld
lua-lgi
lua-lpeg
meson
opencv
ostree
p7zip
python-backcall
python-exceptiongroup
python-fixtures
python-flask-compress
python-flask-gravatar
python-flask-migrate
python-flask-paranoid
python-flask-security-too
python-flit-core
python-gssapi
python-hurry-filesize
python-jaraco.test
python-ldap3
python-mock
python-poetry-dynamic-versioning
python-rapidfuzz-capi
python-rfc3986
python-scikit-build
python-setuptools-scm
python-simplejson
python-sshtunnel
python-testpath
python-testtools
python-toml
python-xlib
rpcsvc-proto
rustup
scdoc
sysfsutils
tinycompress
tllist
vala
vulkan-validation-layers
wlroots
xtrans $argv
        
end
