function pac_autoremove --wraps=sudo\ pacman\ -Rcs\ aquamarine-git-debug\nasar\nautoconf-archive\naylurs-gtk-shell-debug\ncatch2\ncheck\ncloudflared-bin-debug\ndoxygen\nelectron\nelectron28\nelectron29\nextra-cmake-modules\nffnvcodec-headers\nfswatch-debug\ngo\ngtkmm3\nhelp2man\nhttpdirfs\nhttpdirfs-debug\nhyprcursor-git-debug\nhypridle-git-debug\nhyprland-git-debug\nhyprlang-git-debug\nhyprlock-git-debug\nhyprpaper-git-debug\nhyprpicker-git-debug\nhyprutils-git-debug\nhyprwayland-scanner-git-debug\nimagemagick\niniparser\nkdoctools\nki18n5\nknotifications\nknotifications5\nkwidgetsaddons\nkwidgetsaddons5\nlazydocker-bin-debug\nlib32-vulkan-icd-loader\nlibtermkey\nlua51\nntfs-3g-system-compression-debug\np7zip\npython-clickgen\npython-importlib-metadata\npython-ply\npython-poetry-dynamic-versioning\npython-pydantic\npython-pyrsistent\nrust\nsassc\nscdoc\nslack-desktop-wayland-debug\nsmartgit-debug\ntableplus-debug\nteams-debug\ntree-sitter-bash\ntree-sitter-python\nttf-jetbrains-mono\nttf-roboto\ntypescript\nvala\nvercel-debug\nvulkan-validation-layers\nwezterm-git-debug\nwlroots\nxdg-desktop-portal-hyprland-git-debug\nxorg-xinput\nxwaylandvideobridge-git-debug\nyay-debug --description alias\ pac_autoremove\ sudo\ pacman\ -Rcs\ aquamarine-git-debug\nasar\nautoconf-archive\naylurs-gtk-shell-debug\ncatch2\ncheck\ncloudflared-bin-debug\ndoxygen\nelectron\nelectron28\nelectron29\nextra-cmake-modules\nffnvcodec-headers\nfswatch-debug\ngo\ngtkmm3\nhelp2man\nhttpdirfs\nhttpdirfs-debug\nhyprcursor-git-debug\nhypridle-git-debug\nhyprland-git-debug\nhyprlang-git-debug\nhyprlock-git-debug\nhyprpaper-git-debug\nhyprpicker-git-debug\nhyprutils-git-debug\nhyprwayland-scanner-git-debug\nimagemagick\niniparser\nkdoctools\nki18n5\nknotifications\nknotifications5\nkwidgetsaddons\nkwidgetsaddons5\nlazydocker-bin-debug\nlib32-vulkan-icd-loader\nlibtermkey\nlua51\nntfs-3g-system-compression-debug\np7zip\npython-clickgen\npython-importlib-metadata\npython-ply\npython-poetry-dynamic-versioning\npython-pydantic\npython-pyrsistent\nrust\nsassc\nscdoc\nslack-desktop-wayland-debug\nsmartgit-debug\ntableplus-debug\nteams-debug\ntree-sitter-bash\ntree-sitter-python\nttf-jetbrains-mono\nttf-roboto\ntypescript\nvala\nvercel-debug\nvulkan-validation-layers\nwezterm-git-debug\nwlroots\nxdg-desktop-portal-hyprland-git-debug\nxorg-xinput\nxwaylandvideobridge-git-debug\nyay-debug
  sudo pacman -Rcs aquamarine-git-debug
asar
autoconf-archive
aylurs-gtk-shell-debug
catch2
check
cloudflared-bin-debug
doxygen
electron
electron28
electron29
extra-cmake-modules
ffnvcodec-headers
fswatch-debug
go
gtkmm3
help2man
httpdirfs
httpdirfs-debug
hyprcursor-git-debug
hypridle-git-debug
hyprland-git-debug
hyprlang-git-debug
hyprlock-git-debug
hyprpaper-git-debug
hyprpicker-git-debug
hyprutils-git-debug
hyprwayland-scanner-git-debug
imagemagick
iniparser
kdoctools
ki18n5
knotifications
knotifications5
kwidgetsaddons
kwidgetsaddons5
lazydocker-bin-debug
lib32-vulkan-icd-loader
libtermkey
lua51
ntfs-3g-system-compression-debug
p7zip
python-clickgen
python-importlib-metadata
python-ply
python-poetry-dynamic-versioning
python-pydantic
python-pyrsistent
rust
sassc
scdoc
slack-desktop-wayland-debug
smartgit-debug
tableplus-debug
teams-debug
tree-sitter-bash
tree-sitter-python
ttf-jetbrains-mono
ttf-roboto
typescript
vala
vercel-debug
vulkan-validation-layers
wezterm-git-debug
wlroots
xdg-desktop-portal-hyprland-git-debug
xorg-xinput
xwaylandvideobridge-git-debug
yay-debug $argv
        
end
