theme {
  # color_scheme = /home/nickp_real/.local/share/color-schemes/onedark.colors
  color_scheme = /usr/share/color-schemes/Darkly.colors
  icon_theme = Papirus
  style = Darkly
  font = Google Sans Display
  font_size = 9
}
