$mainMod = SUPER
$terminal = foot
$fileExlorer = nemo

# Decoration
# Blur
$blurEnabled = true
$rounding = 8
$blurSize = 8
$blurPasses = 2
$blurXray = true

# Shadow
$shadowEnabled = true
$shadowRange = 20
$shadowRenderPower = 3
$shadowColor = rgba(1a1a1aee)

# General
$gapsIn = 4
$gapsOut = 8
$borderSize = 2
$activeBorderColor = rgba(33ccffee) rgba(00ff99ee) 45deg
$inactiveBorderColor = rgba(595959aa)
