# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$all\
$fill\
$battery\
$time\
$line_break\
$character
"""
command_timeout = 2000

[fill]
symbol = " "

[git_status]
disabled = false

[time]
disabled = false
format = '🕙 [\[$time\]]($style) '
time_format = "%r"

[gcloud]
disabled = true

# [aws]
# symbol = "  "

# [conda]
# symbol = " "

# [dart]
# symbol = " "

# [directory]
# read_only = " 󰌾"

# [docker_context]
# symbol = " "

# [elixir]
# symbol = " "

# [elm]
# symbol = " "

# [git_branch]
# symbol = " "

# [golang]
# symbol = " "

# [hg_branch]
# symbol = " "

# [java]
# symbol = " "

# [julia]
# symbol = " "

# [memory_usage]
# symbol = "󰍛 "

# [nim]
# symbol = "󰆥 "

# [nix_shell]
# symbol = " "

# [package]
# symbol = "󰏗 "

# [perl]
# symbol = " "

# [php]
# symbol = " "

# [python]
# symbol = " "

# [ruby]
# symbol = " "

# [rust]
# symbol = " "

# [scala]
# symbol = " "

# [shlvl]
# symbol = " "

# [swift]
# symbol = " "
