decoration {
    rounding = $rounding

    blur {
        enabled = $blurEnabled
        size = $blurSize
        passes = $blurPasses
        xray = $blurXray
    }

    shadow {
        enabled = $shadowEnabled
        range = $shadowRange
        render_power = $shadowRenderPower
        color = $shadowColor
    }
}
