windowrule = float match:title .*Emulator.*
windowrule = float match:class rofi
windowrule = float match:class .*polkit-kde-authentication.*
windowrule = float match:class pavucontrol
windowrule = float match:title Open File
windowrule = workspace 4 silent, match:class Slack
windowrule = workspace 5 silent, match:class spotify

# xwaylandvideobridge
windowrule {
    name = xwayland-video-bridge-fixes
    match:class = xwaylandvideobridge

    no_initial_focus = true
    no_focus = true
    no_anim = true
    no_blur = true
    max_size = 1 1
    opacity = 0.0
}
